baseURL = "https://jenciso.github.io"
languageCode = "en-us"
title = "Tech-Blog"
theme = "mediumish"
summaryLength = 25
copyright = "Juan Enciso - All rights reserved"
enableEmoji = true
publishDir = "docs"
disqusShortname = "jenciso-github-io" # Enable comments by entering your Disqus shortname
googleAnalytics = "UA-106539950-1" # Enable Google Analytics by entering your tracking id
pygmentsCodeFences = false 
pygmentsCodefencesGuessSyntax = false
pygmentsUseClasses = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  logo = "/images/icon_cmd.png"
  description = "Sharing my tech stories"
  #mailchimp = "https://gmail.us20.list-manage.com/subscribe/post?u=fcd0d13593259ece3901cc6b1&amp;id=658aa507ab"
  asciinema = false
  copy2clipboard = false

[params.author]
  name = "Juan Enciso"
  thumbnail = "/images/author.png"
  description = "IT Architect, SRE Engineer, DevOps Tools Trainer"

[params.index]
  picture = "/images/author.png"
  title = "Juan Enciso"
  subtitle = "IT Architect | SRE Leader Engineer | Devops Technical Trainer"
  mdtext = '''
Love building distributed systems, writing code in bash, python, and go,
engaging share colaboration culture and learning new things
###### **Open Source, Technical Leadership, Automation, People**
'''
  alertbar = true

[params.social]
  github = "jenciso"
  linkedin = "juanenciso"
  medium = "jenciso"
  twitter = "jenciso"
  instagram = "jencisoc"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 200
    url = "/"
[[menu.main]]
    name = "CV"
    identifier = "cv"
    weight = 200
    url = "/cv"
